{
 "title": "Chia Farming",
 "description": "Farming dashboard for use with chia-exporter",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "DS_LOKI", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Synced",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_full_node_node_synced", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Height",
   "type": "stat",
   "description": "Number of blocks in the blockchain",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint) (\n    topk(1, \n        chia_blockchain_height !=0 or \n        chia_full_node_node_height !=0\n    )\n)",
     "legendFormat": "Height"
    }
   ]
  },
  {
   "title": "Eligible Plots (per signage point)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(chia_harvester_total_eligible_plots[5m])) * 9.375",
     "legendFormat": "Filter Passes"
    }
   ]
  },
  {
   "title": "Time to win",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "18.75 / ( (sum(chia_harvester_plot_filesize)/1048576) / sum(chia_full_node_netspace_mib) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partials (24 hr)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(chia_farmer_submitted_partials[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Wins (24 hr)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(chia_farmer_proofs_found[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Wins (week)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(chia_farmer_proofs_found[7d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Full node peer count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_full_node_connection_count{node_type=\"full_node\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Difficulty",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_full_node_difficulty", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mempool size (5 min ave)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 3 },
   "targets": [
    {
     "expr": "round(avg_over_time(chia_full_node_mempool_size[5m]))",
     "legendFormat": "Mempool Size"
    }
   ]
  },
  {
   "title": "Estimated Daily Rewards",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "xch" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(chia_harvester_plot_filesize)/1048576) / sum(chia_full_node_netspace_mib) * 4608 * 2",
     "legendFormat": "xch"
    }
   ]
  },
  {
   "title": "Estimated Monthly Rewards",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "xch" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(chia_harvester_plot_filesize)/1048576) / sum(chia_full_node_netspace_mib) * 4608 * 2 * (365/12)",
     "legendFormat": "xch"
    }
   ]
  },
  {
   "title": "Total Size All Plots",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(chia_harvester_plot_filesize)",
     "legendFormat": "{{type}} {{instance}}"
    }
   ]
  },
  {
   "title": "Total plots",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(chia_harvester_total_plots)",
     "legendFormat": "Total plots  {{instance}}"
    }
   ]
  },
  {
   "title": "Blockchain TPS",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum without(application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint) (\r\n  topk(1, chia_full_node_block_cost{network=\"mainnet\"}) / 5000000\r\n) * \r\nsum without(application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint) (\r\n  bottomk(1,  \r\n    rate(chia_full_node_node_height{network=\"mainnet\"}[5m]) and on (instance) (chia_full_node_node_synced{network=\"mainnet\"} == 1)\r\n  )\r\n) / 3",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Block Fees",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "xch" } },
   "targets": [
    {
     "expr": "sum without(application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint) (\r\n  topk(1, chia_full_node_block_fees{network=\"mainnet\"})\r\n) / 1000000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Size All Plots",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_harvester_plot_filesize", "legendFormat": "{{type}} {{instance}}" }
   ]
  },
  {
   "title": "Farmer Submitted Partials",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "targets": [
    { "expr": "chia_farmer_submitted_partials", "legendFormat": "{{network}} {{instance}}" }
   ]
  },
  {
   "title": "Mempool Cost",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "targets": [
    { "expr": "chia_full_node_mempool_cost", "legendFormat": "Cost" }
   ]
  },
  {
   "title": "Full Node Validation Time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "chia_full_node_validation_time", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Total plots",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "targets": [
    { "expr": "chia_harvester_total_plots", "legendFormat": "Total plots  {{instance}}" }
   ]
  },
  {
   "title": "Harvester Total Found Proofs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "chia_harvester_total_found_proofs",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Signage Points per 9.375 seconds (target)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "max(rate(chia_full_node_total_signage_points[5m])) * 9.375",
     "legendFormat": "Signage Points"
    }
   ]
  },
  {
   "title": "Full Node Validation Time (Histogram)",
   "type": "histogram",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "chia_full_node_validation_time", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Harvester Lookup Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "chia_harvester_last_lookup_time",
     "legendFormat": "Harvester Latency  {{instance}}"
    }
   ]
  },
  {
   "title": "Lookup Times (Histogram)",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "chia_harvester_last_lookup_time",
     "legendFormat": "Latency  {{instance}}"
    }
   ]
  },
  {
   "title": "Netspace",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    { "expr": "chia_full_node_netspace_mib", "legendFormat": "{{network}}" }
   ]
  },
  {
   "title": "Height",
   "type": "timeseries",
   "description": "Height: Number of blocks in the blockchain\n\nBlocks per 18.75 seconds:\nBased on 86400 seconds in a day and a target of 4608 blocks in a day, we expect a block every 18.75 seconds. The rate of blocks is calculated based on a rolling one hour window.\n\nIf this number is less than 1, the chain is moving slower than the target, and you would expect difficulty to decrease at the next adjustment.\n\nIf the number is greater than 1,  the chain is moving faster than the target and you would expect difficulty to increase at the next adjustment.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum without(application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint) (\n  topk(1, \n    chia_blockchain_height or\n    chia_full_node_node_height !=0\n  )\n)",
     "legendFormat": "Height"
    },
    {
     "expr": "((\n  sum without(application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint) (\n    topk(1, \n      chia_blockchain_height or\n      chia_full_node_node_height\n    ) != 0\n  ) - \n  sum without(application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint) (\n    topk(1, \n      chia_blockchain_height offset 3600s or\n      chia_full_node_node_height offset 3600s\n    ) != 0\n  )\n)/(3600/18.75))",
     "legendFormat": "Blocks per 18.75 seconds"
    }
   ]
  },
  {
   "title": "Found Proof Times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(1.0,{job=\"chia_harvest\"} |= `proofs` | pattern `<timestamp> <_> <_> <_> <plots> plots <_> Found <proofs> proofs. Time: <time> <_>` | proofs > 0 |  unwrap time [$__interval]) by (host)"
    }
   ]
  },
  {
   "title": "Proofs and Qualities",
   "type": "logs",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "{job=\"chia_harvest\"} |= `proofs` | pattern `<timestamp> <_> <_> <_> <plots> plots <_> Found <proofs> proofs. Time: <time> <_>` | proofs > 0 | line_format `{{.timestamp}} {{.host}} Found {{.proofs}} proof. Time: {{.time}}s. {{.plots}} eligible plots.`",
     "legendFormat": "{{host}}",
     "maxLines": 1000
    },
    {
     "expr": "{job=\"chia_harvest\"} |= `qualities` | pattern `<timestamp> <_> <_> <_> <_> <_> <_> <_> <_> <_> <_> <time>. <_>` | line_format `{{.timestamp}} {{.host}} Looking up quality took {{.time}}s.`"
    }
   ]
  },
  {
   "title": "Farmer Proofs Found",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 34 },
   "targets": [
    { "expr": "chia_farmer_proofs_found", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Qualities Warning Times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(1,{job=\"chia_harvest\"} |= `qualities` | pattern `<timestamp> <_> <_> <_> <_> <_> <_> <_> <_> <_> <_> <time>. <_>` | unwrap time [$__interval]) by (host)"
    }
   ]
  }
 ]
}