---
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: tenant1

sscrape_configs:
  - job_name: chia
    static_configs:
    - targets:
      - localhost
      labels:
        host: chia01
        job: chia_harvest
        __path__: /chia/harvest/mainnet/log/debug.log


